import { chromium } from 'playwright';
const [,, url, out, full] = process.argv;
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 950 }, deviceScaleFactor: 2 });
await p.goto(url, { waitUntil: 'networkidle', timeout: 60000 });
await p.waitForTimeout(1200);
await p.screenshot({ path: out, fullPage: full === 'full' });
const errs = [];
p.on('console', m => m.type() === 'error' && errs.push(m.text()));
console.log('shot', out, errs.length ? 'ERRORS: ' + errs.join(' | ') : 'no console errors');
await b.close();
